# Generated by Django 3.2.7 on 2021-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RidesPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppw', models.IntegerField()),
                ('pn', models.IntegerField()),
                ('mi', models.IntegerField()),
                ('appm', models.IntegerField()),
                ('res', models.CharField(max_length=20)),
            ],
        ),
    ]
